### ISSUE TITLE
Add endpoint validation

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/cluster-validator#17]
Since componentstatuses is getting deprecated, In order to validate etcd and other control plane components we need to support endpoint validation e.g.

```bash
kubectl get --raw='/readyz?verbose'
[+]ping ok
[+]log ok
[+]etcd ok
[+]informer-sync ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/priority-and-fairness-filter ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]poststarthook/priority-and-fairness-config-producer ok
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/aggregator-reload-proxy-client-cert ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
[+]shutdown ok
readyz check passed
```

API can be something like:
```yaml
apiVersion: v1alpha1
kind: ClusterValidator
metadata:
  name: validation
spec:
  configuration:
    <..configuration..>
  resources:
    <..cluster resources..>
  endpoints:
      # Support querying an endpoint from inside the cluster? similar to kubectl get --raw
    - cluster: "/readyz?include=etcd&verbose" # would be great if this can be supported
      # We should also add a generic option for any endpoint, but could also allow hitting the API externally
      url: "https://my-eks-api.elb.us-west-2.amazonaws.com/readyz?include=etcd&verbose"
      # acceptable HTTP codes
      codes: 
      - 200
      required: true
```
