### ISSUE TITLE
Evaluate switching to using a watch instead of indivdual calls

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/cluster-validator#6]
Currently we make calls according to the polling configuration:
```
  configuration:
    successThreshold: 10
    failureThreshold: 10 
    interval: 1s
```

In this case we would need 10 successful calls to succeed, or 10 failed calls to fail, with 1 second interval.

Instead we could make the configuration more suitable for using watches:
```
  configuration:
    successDuration: 10s
    failureDuration: 10s
```

We could make a single call per resource to open a watch, and use time tickers to count the time we are in success/fail state instead.
