### ISSUE TITLE
Switch to using JSONPath from client-go

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/cluster-validator#7]
Right now we have our own implementation of JSONPath which is quite simple, and does not support iterators of lists, etc.
We can leverage the JSONPath library from client-go:
https://github.com/kubernetes/client-go/tree/master/util/jsonpath

This would provide support for more complex queries that includes lists, etc.

**Comment by eytan-avisror** [comment]
Current implementation

https://github.com/keikoproj/cluster-validator/blob/6a52e6df726b93db385ca0a6668948a14b11050d/pkg/api/v1alpha1/resource.go#L42-L53

Field Validation:
https://github.com/keikoproj/cluster-validator/blob/6a52e6df726b93db385ca0a6668948a14b11050d/pkg/client/validator.go#L241-L280

**Comment by eytan-avisror** [comment]
Since we will be accepting jsonpath as a more complex statement seems will be easier to take values separately, e.g. instead of 

```
    fields: 
    - path: "{.containerStatuses[*].state.running.startedAt=*"
    - path: "{.status.phase}=succeeded,running"
 ```

It would probably be easier to values to the struct

```
    fields: 
    - path: "{.containerStatuses[*].state.running.startedAt" # default to "*" when values not provided
   
    - path: "{.status.phase}"
      values:
      - succeeded
      - running
  ```
