### ISSUE TITLE
Add annotation / label selectors

### ISSUE THREAD

**Issue by eytan-avisror** [keikoproj/cluster-validator#9]
We should add annotation / label selectors for convenience under scope.

For example, instead of a basic namespaced scope:
```
  - name: pods
    apiVersion: v1
    names:
      include: 
      - "*"
    namespaces:
      include:
      - "kube-system"
    fields: 
    - path: .status.phase=running
    required: true
```

We can add scope for annotations and/or labels under scope

```
  - name: pods
    apiVersion: v1
    annotations:
      include:
      - some-key: some-value
    labels:
      include:
      - some-key: some-value
    namespaces:
      include:
      - "kube-system"
      
    fields: 
    - path: .status.phase=running
    required: true
```

This would be particularly useful in the case where resources have names that are less relevant, such as nodes, but scope selection would make more sense using labels or annotations e.g. all nodes with a specific role
